<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!-- Infrastructure implementa contratos da Application e persiste entidades do Domain. -->
    <ProjectReference Include="../OrderManagement.Application/OrderManagement.Application.csproj" />
    <ProjectReference Include="../OrderManagement.Domain/OrderManagement.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>
</Project>
