<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <!-- Application conhece somente o núcleo de domínio, respeitando a direção das dependências. -->
    <ProjectReference Include="../OrderManagement.Domain/OrderManagement.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
